version: '3'
services:
  frontend:
    build: ./frontend/.devcontainer
    volumes:
      - simple-shop-volume:/workspace
    command: /bin/sh -c "while sleep 1000; do :; done"
    links:
      - backend

  backend:
    build: ./backend/.devcontainer
    volumes:
      - simple-shop-volume:/workspace
    command: /bin/sh -c "while sleep 1000; do :; done"

volumes:
  simple-shop-volume:
